### ISSUE TITLE
results.valueの型がおかしい？

### ISSUE THREAD

**Issue by takumus** [ArakiTakaki/promise-serial#17]
README.mdのサンプルコードを試してみました。
`console.log(await results.value)`の型は本来`string[]`になって欲しいところですが、`Promise<string>[]`になっているようです。
ただ、実行時にはstringになっています。
型定義が間違えているのかもしれません。

```ts
// キャンセル無
const items = ['done 1', 'done 2', 'done 3', 'done 4'];
const results = promiseSerial(items.map((val) => () => waitForPromise(100, val)));
const values = await results.value;
const firstValue = values[0];
console.log(typeof firstValue); // 実行時stringと出ますが、vscodeではPromise<string>となっている。
```

**Comment by takumus** [comment]
`cancel()`の戻り値も上記と同じでした。`Promise<number>[]`になっていますが、実際はnumber[]です。
```ts
const values = await result.cancel();
console.log(values) // number[]なのにvscodeだとPromise<number>[]
```

**Comment by ArakiTakaki** [comment]
ありがとうございます！
型定義対応し、Issueに原因を追記します。

**Comment by ArakiTakaki** [comment]
@takumus 
対応完了しました。
尚、挙動自体の変更なためメジャーバージョン上げました！

https://github.com/ArakiTakaki/promise-serial/commit/af6e42ddbc4168b29bb2972b0f0bb6b44b3e4247

https://github.com/ArakiTakaki/promise-serial/commit/bd60503c3798464cd1782dd7ef7557a0c2fdc555

**Comment by ArakiTakaki** [comment]
まだ治っていない。
2.0で続行

**Comment by takumus** [comment]
`.value` は2.0.1で治っているの確認しました！
ただ、こちらがまだのようです。
https://github.com/ArakiTakaki/promise-serial/issues/17#issuecomment-1120176127
